### ISSUE TITLE
admins that dont get angrie

### ISSUE THREAD

**Issue by UntrustWasTaken** [SerialFlame/Server#3]
and not ban ppl for disagree**Describe the solution you'd like**

**Additional context**

**Servers**
Which server(s) would you like this to happen on?

**Comment by joecollyer** [comment]
This is something that we are working to achieve on SerialFlame. Thank you for your concern.

**Comment by joecollyer** [comment]
Mr Untrust, this has now been solved as admins no longer get angrie.

Thanks for the request, **_SERIALFLAME_**!!!!!!!!!!!!!
From Joe 💯 🍆
